version: '3'

dotenv: ["metadata.env"]
silent: true

vars:
  PYTHON_VERSION:
    sh: "cat .python-version"

tasks:
  lock:
    desc: "Lock requirements"
    cmds:
      - echo "Compiling requirements..."
      - |
        uv pip compile \
        --python {{.PYTHON_VERSION}} \
        --index-strategy "unsafe-best-match" \
        --format "pylock.toml" \
        --output-file "pylock.toml" requirements.in
      - echo
      - echo "👉 Compiled requirements for ComfyUI v${COMFYUI_VERSION} using Python {{.PYTHON_VERSION}}."

  build:
    desc: "Build the docker image"
    cmds:
      - docker buildx bake build --set "*.tags=${COMFYUI_STACK_IMAGE}:latest"

  tests:
    cmds:
      - |
        docker run \
          -it \
          --rm \
          -p 8000:8188 \
          --runtime=nvidia \
          --gpus=all \
          local/comfyui:latest \
            --use-sage-attention

  clean:
    cmds:
      - docker builder prune -a -f
      - docker image prune -a -f

  preview-changelog:
    desc: "Preview next changelog"
    cmds:
      - git cliff -v --bump --unreleased

  release:
    desc: "Create a new release and tag"
    prompt: "You are about to create a new release. Continue ?"
    cmds:
      - scripts/release.sh
      - echo "Now, push commit with tags (git push origin --tags) to create the release."
