version: '3'

dotenv: ["metadata.env"]
silent: true

vars:
  PYTHON_VERSION:
    sh: "cat .python-version"

tasks:
  lock:
    desc: "Lock requirements"
    cmds:
      - echo "Compiling requirements..."
      - |
        uv pip compile \
        --python {{.PYTHON_VERSION}} \
        --index-strategy "unsafe-best-match" \
        --format "pylock.toml" \
        --output-file "pylock.toml" requirements.in
      - echo
      - echo "👉 Compiled requirements for ComfyUI v${COMFYUI_VERSION} using Python {{.PYTHON_VERSION}}."

  build:
    desc: "Build the docker image"
    cmds:
      - docker buildx bake {{.TARGET|  default "test"}}

  push:
    desc: "Push the docker image"
    cmds:
      - docker image push --all-tags ${COMFYUI_STACK_IMAGE}

  tests:
    cmds:
      - |
        docker run \
          -it \
          --rm \
          -p 8000:8188 \
          --runtime=nvidia \
          --gpus=all \
          local/comfyui:latest \
            --use-sage-attention

  clean:
    cmds:
      - docker builder prune -a -f
      - docker image prune -a -f

  changelog:
    desc: "Generate the changelog"
    cmds:
      - git cliff -o CHANGELOG.md
